import "dotenv/config";
import fs from "fs/promises";
import path from "path";

async function main() {
  const storyblokSpaceId = process.env.STORYBLOK_SPACEID;

  if (!storyblokSpaceId) {
    console.error(`
Error: STORYBLOK_SPACE_ID environment variable is not set.
This ID is required to configure Netlify Image CDN for Storyblok.
Please set this environment variable in your Netlify build settings or your local .env file.
Example: STORYBLOK_SPACE_ID=123456
    `);
    process.exit(1); // Exit with an error code
  }

  // This will be the content of the netlify.toml file
  const netlifyTomlContent = `
# This file is auto-generated by scripts/generate-netlify-config.mjs during the build process.
# Do NOT edit this file directly. Your changes will be overwritten.
# Configure STORYBLOK_SPACE_ID in your environment variables.

[build]
  # This is the command Netlify will run to build your site *after* this config is generated.
  command = "astro build" # Or your specific build command for Astro, e.g., "npm run actual_build_logic"
  functions = "netlify/functions" # Adjust if your functions directory is different

[images]
  # Dynamically set from STORYBLOK_SPACE_ID environment variable
  remote_images = ["https://a.storyblok.com/f/${storyblokSpaceId}/.*"]

[dev]
  # targetPort should match your Astro dev server port (default 4321 for Astro)
  # This setting is for 'netlify dev'
  targetPort = 4321

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
`.trimStart(); // trimStart to remove leading newline from template literal

  try {
    fs.writeFile("./netlify.toml", netlifyTomlContent, (err) => {
      if (err) throw err;
      console.log(`Fichier netlify.toml ajouté`);
    });
  } catch (error) {
    console.error("Erreur d'écriture du fichier netlify.toml", error);
  }
}

main();
