# TODO : add remote_images address for Netlify Images (i.e. "https://a.storyblok.com/f/331539/.*")

[build]
  command = "npm run build"
  functions = "netlify/functions"
[images]
  remote_images = ["https://a.storyblok.com/f/339478/.*"]
[dev]
  targetPort = 4321

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

  
  

