# TODO : add remote_images address for Netlify Images (i.e. https://a.storyblok.com/f/331539/.*)

[build]
  command = "npm run build"
  functions = "netlify/functions"
[images]
  remote_images = []
[dev]
  targetPort = 4321
  
  

